trigger:
- none

pr:
  branches:
    include:
    - develop
  paths:
     exclude:
     - TestNotBuildApp/*

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore tests/Tests.Core/Tests.Core.csproj
- task: DotNetCoreCLI@2
  displayName: Build $(buildConfiguration)
  inputs:
    command: build
    projects: '**/pipelines-dotnet-core.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
- task: DotNetCoreCLI@2
  displayName: Tests
  inputs:
    command: test
    projects: '**/tests/Tests.Core/Tests.Core.csproj' 
    arguments: '--configuration $(buildConfiguration) --filter TestCategory="Api"'